headersize = 100000
headertimeout = "100s"
forcedownload = "^image/.*$"  # regexp with mimetypes, which will be downloaded
maxdownloadsize = 4294967295 # max. 4GB downloads
logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
accesslog = "" # http access log file
addr = "localhost:8000"
insecurecert = false
certpem = "" # tls client certificate file in PEM format
keypem = "" # tls client key file in PEM format
jwtkey = "swordfish"
jwtalg = ["HS256", "HS384", "HS512"] # "hs256" "hs384" "hs512" "es256" "es384" "es512" "ps256" "ps384" "ps512"
errorTemplate = "web/template/error.gohtml" # error message for memoHandler
tempDir = "/mnt/c/temp/"

[Indexer.MimeRelevance]
# relevance < 100: rate down
# relevance > 100: rate up
# default = 100
    [Indexer.MimeRelevance.1]
        regexp = "^application/octet-stream$"
        weight = 1
    [Indexer.MimeRelevance.2]
        regexp = "^text/plain$"
        weight = 3
    [Indexer.MimeRelevance.3]
        regexp = "^audio/mpeg$"
        weight = 4
    [Indexer.MimeRelevance.4]
        regexp = "^video/mpeg$"
        weight = 4
    [Indexer.MimeRelevance.5]
        regexp = "^text/.+$"
        weight = 4
    [Indexer.MimeRelevance.6]
        regexp = "^application/.+"
        weight = 2
    [Indexer.MimeRelevance.7]
        regexp = "^.+/x-.+"
        weight = 80

[Indexer.nsrl]
badger = "/mnt/c/temp/nsrl"
enabled = false

[Indexer.XML]
Enabled=true
[Indexer.XML.Format.FineReader10]
Element = "document"
Attributes.xmlns = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml"
Type = "ocr"
Subtype = "FineReader10"
Mime = "application/xml"
[Indexer.XML.Format.mets]
Element = "mets:mets"
Regexp = true
Attributes."xmlns:mets" = "^https?://www.loc.gov/METS/?$"
Type = "metadata"
Subtype = "METS"
Mime = "application/xml"
[Indexer.XML.Format.mei]
Element = "mei"
Attributes.xmlns = "http://www.music-encoding.org/ns/mei"
Type = "audio"
Subtype = "mei"
Mime = "application/xml"


[Indexer.Siegfried]
enabled = true
signaturefile = ""
[Indexer.Siegfried.MimeMap]
"x-fmt/92" = "image/psd"
"fmt/134" = "audio/mp3"
"x-fmt/184" = "image/x-sun-raster"
"fmt/202" = "image/x-nikon-nef"
"fmt/211" = "image/x-photo-cd"
"x-fmt/383" = "image/fits"
"fmt/405" = "image/x-portable-anymap"
"fmt/406" = "image/x-portable-graymap"
"fmt/408" = "image/x-portable-pixmap"
"fmt/436" = "image/x-adobe-dng"
"fmt/437" = "image/x-adobe-dng"
"fmt/592" = "image/x-canon-cr2"
"fmt/642" = "image/x-raw-fuji"
"fmt/662" = "image/x-raw-panasonic"
"fmt/668" = "image/x-olympus-orf"
"fmt/986" = "text/xmp"
"fmt/1001" = "image/x-exr"
"fmt/1040" = "image/vnd.ms-dds"
"fmt/1781" = "image/x-pentax-pef"

[Indexer.Siegfried.TypeMap."fmt/483"]
Type = "text"
Subtype = "epub"

[Indexer.clamav]
    enabled = true
    clamscan = "/usr/bin/clamdscan"
    wsl = false
    timeout = "15s"


[Indexer.FFMPEG]
    ffprobe = ""
    wsl = false  # true, if executable is within linux subsystem on windows
    timeout = "25s"
    online = true
    enabled = true
    [[Indexer.FFMPEG.Mime]]
        video = false
        audio = true
        format = "mov,mp4,m4a,3gp,3g2,mj2"
        mime = "audio/mp4"
    [[Indexer.FFMPEG.Mime]]
        video = true
        audio = true
        format = "mov,mp4,m4a,3gp,3g2,mj2"
        mime = "video/mp4"
    [[Indexer.FFMPEG.Mime]]
        video = true
        audio = false
        format = "mov,mp4,m4a,3gp,3g2,mj2"
        mime = "video/mp4"

[Indexer.ImageMagick]
identify = ""
convert = ""
wsl = false  # true, if executable is within linux subsystem on windows
timeout = "480s"
online = true
enabled = true

[Indexer.Tika]
    address = ""
    #address = "http://localhost:9998/rmeta/text"
    timeout = "10s"
    regexpMime = "^." # ""^application/"  # regexp for mimetype, which are used for tika queries
    regexpMimeNot = "^(audio|video|image)/"
    online = true
    enabled = true

[[Indexer.External]]
name = "validateav"
address = "http://localhost:8083/validateav/[[PATH]]"
calltype = "EACTURL"
mimetype = "^(video|audio)/.*"
ActionCapabilities = ["ACTFILE"]

[[Indexer.External]]
name = "exif"
address = "http://localhost:8083/exif/[[PATH]]"
calltype = "EACTURL"
mimetype = ".*"
ActionCapabilities = ["ACTFILE"]

[[Indexer.External]]
name = "validateimage"
address = "http://localhost:8083/validateimage/[[PATH]]"
calltype = "EACTURL"
mimetype = "^image/.*"
ActionCapabilities = ["ACTFILE"]

[[Indexer.External]]
name = "histogram"
address = "http://localhost:8083/histogram/[[PATH]]"
calltype = "EACTURL"
mimetype = "^image/.*"
ActionCapabilities = ["ACTFILE"]
